pipeline:
  name: Provision terraform
  identifier: Provision_terraform
  projectIdentifier: CICD_NodeJs_Terraform_ECS
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Provision
        identifier: Provision
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: aws_terraform
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  timeout: 10m
                  spec:
                    command: init
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  timeout: 10m
                  spec:
                    command: plan
              - step:
                  type: IACMApproval
                  name: Approve Plan.
                  identifier: Approve_Plan
                  spec:
                    autoApprove: false
                  timeout: 1h
              - step:
                  type: IACMTerraformPlugin
                  name: apply
                  identifier: apply
                  timeout: 10m
                  spec:
                    command: apply
        tags: {}
